repos:
- repo: local
  hooks:
  - id: Test pre-commit
    name: Run Test pre-commit
    entry: python
    language: system
    args: [pre_commit_test.py]
  - id: Test commit-msg
    name: Run Test commit-msg
    entry: python
    language: system
    args: [commit_msg_test.py]
  - id: Test post-commit
    name: Run Test post-commit
    entry: python
    language: system
    args: [post_commit_test.py]
  - id: Test pre-push
    name: Run Test pre-push
    entry: python
    language: system
    args: [pre_push_test.py]